# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_notification_project_alter_notification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pendiente'),
                    ('ACCEPTED', 'Aceptada'),
                    ('REJECTED', 'Rechazada'),
                ],
                default='ACCEPTED',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pendiente'),
                    ('ACCEPTED', 'Aceptada'),
                    ('REJECTED', 'Rechazada'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
